### ISSUE TITLE
tiro Consumes too much RAM

### ISSUE THREAD

**Issue by jeffswt** [xmcp/tiroFinale#2]
Possibly due to the memory pool list, tiro consumes memory once reached a new website.

Supposedly, I was wondering if you could add a frequency statistic module and remove infrequent pool indices and thus freeing memory once memory is considerably filling up.

Like I has been using for several days and it flew up to about 200MB...

**Don't tell me to restart tiro!**

**Comment by xmcp** [comment]
yes. _just restart tiro_. or add more RAM.
re-open this issue once tiro used 2GB+ RAM.

request pooling is handled by `requests`; thus it's none of my business.
try to reduce `const.POOLSIZE` if u really trasure your RAM.
