### ISSUE TITLE
tiro's (un)Intelligent Circumvention System is outdated

### ISSUE THREAD

**Issue by jeffswt** [xmcp/tiroFinale#3]
in the gfwlist.py you should add the following items as for now:

```
"amazonaws.com",
"github-cloud.amazonaws.com",
"s3.amazonaws.com",
```

---

I was wondering if <del>gaiError / getaddrinfo failed</del> **`Connection aborted`** was thrown or timeout you could redirect the connection to Finale?

**Comment by xmcp** [comment]
i'm using [CaledoniaProject/GFWList](https://github.com/CaledoniaProject/GFWList), which is outdated.
will try to implement auto redirecting soon
